name: Run Telegram Parser and Scraper

on:
  # Позволяет запускать воркфлоу вручную через интерфейс GitHub Actions
  workflow_dispatch:
    inputs:
      phone_number:
        description: 'Ваш номер телефона Telegram (в формате +7XXXXXXXXXX)'
        required: true
        default: '+7' 
      auth_code:
        description: 'Код авторизации Telegram (требуется только для второго запуска)'
        required: false
        default: 'none' # Маркер для первого запуска

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies (Telethon)
        run: pip install telethon

      - name: Run Telegram Scraper (Двухэтапная авторизация)
        # КРИТИЧЕСКОЕ ИЗМЕНЕНИЕ: Передаем данные напрямую через аргументы
        run: |
          python3 main_parser.py \
            --phone ${{ github.event.inputs.phone_number }} \
            --code ${{ github.event.inputs.auth_code }}
        env:
          # Секретные ключи из настроек репозитория
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
