name: Telegram Parser

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          # Устанавливаем только нужные библиотеки (без Jupyter)
          pip install telethon requests nest_asyncio
          
      # ИЗМЕНЕНИЕ: Запускаем чистый Python-скрипт main_parser.py
      - name: Execute Telegram Parser Script
        run: |
          python main_parser.py 
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
