name: 🚀 Telegram Parser & n8n Sender (Сессионный файл)

on:
  # Позволяет запускать воркфлоу вручную через интерфейс GitHub Actions
  workflow_dispatch:
    inputs:
      webhook_url:
        description: 'URL вашего n8n Webhook'
        required: true
        default: 'https://your.n8n.webhook.url'

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      - run: pip install telethon requests

      - name: Run Telegram Parser and Send to n8n
        # !!! ЭТА КОМАНДА ЗАПУСКАЕТ НОВЫЙ СКРИПТ main_parser.py !!!
        run: python3 main_parser.py
        env:
          # Передача секретов и URL Webhook в скрипт
          API_ID: ${{ secrets.API_ID }} 
          API_HASH: ${{ secrets.API_HASH }}
          N8N_WEBHOOK_URL: ${{ github.event.inputs.webhook_url }}
