name: Run Telegram Parser and Scraper

on:
  # Позволяет запускать воркфлоу вручную через интерфейс GitHub Actions
  workflow_dispatch:
    inputs:
      phone_number:
        description: 'Ваш номер телефона Telegram (в формате +7XXXXXXXXXX)'
        required: true
        default: '+7' 
      auth_code:
        description: 'Код авторизации Telegram (требуется только для второго запуска)'
        required: false
        default: ''

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Install dependencies (Telethon)
        run: pip install telethon

      - name: Run Telegram Scraper (Двухэтапная авторизация)
        # ИСПРАВЛЕНИЕ: Теперь запускаем ваш файл main_parser.py
        run: python3 main_parser.py
        env:
          # Секретные ключи из настроек репозитория
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          
          # Передача входных данных Workflow в переменные среды скрипта Python
          PHONE_NUMBER: ${{ github.event.inputs.phone_number }}
          AUTH_CODE: ${{ github.event.inputs.auth_code }}
