name: Run Colab Notebook and Trigger n8n

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install jupyter
          pip install papermill
          pip install telethon requests Pillow opencv-python

      - name: Run Notebook (Parses Data to a File)
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: |
          # ВНИМАНИЕ: Если ваш Notebook сохраняет данные в файл (например, results.json), 
          # то именно этот файл вам нужно будет использовать для отправки в n8n.
          papermill tt.ipynb output.ipynb
          
      # ------------------------------------------------------------------
      # ИЗМЕНЕННЫЙ БЛОК: Отправляем Run ID в теле JSON.
      # n8n сможет легко его прочитать из поля "body".
      # ------------------------------------------------------------------
      - name: Send trigger and Run ID to n8n
        if: success() # Запускать, только если предыдущие шаги прошли успешно
        env:
          N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }} # Используем секрет
          RUN_ID: ${{ github.run_id }} # Получаем текущий ID выполнения
        run: |
          echo "Отправка POST-запроса на Webhook n8n с Run ID: $RUN_ID"
          curl -X POST "${N8N_WEBHOOK_URL}" \
               -H "Content-Type: application/json" \
               -d "{\"run_id\": \"$RUN_ID\"}" # Передаем ID в теле JSON
          echo "Триггер отправлен. Проверьте n8n на новое выполнение."
